language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t eugenepoletski/docker-03 -f Dockerfile.dev .

script:
  - docker run -e CI=true eugenepoletski/docker-03 npm run test